# Generated by Django 5.2 on 2025-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='categoria',
            field=models.CharField(choices=[('romance', 'Romance'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('ciencia', 'Ciencia Ficción'), ('terror', 'Terror'), ('drama', 'Drama'), ('comedia', 'Comedia'), ('fantasia', 'Fantasía')], default='Accion', max_length=20),
            preserve_default=False,
        ),
    ]
