# Generated by Django 5.2 on 2025-05-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
