# Generated by Django 5.2 on 2025-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='libros',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='libros',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='libros',
            name='ejemplares_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libros',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AddField(
            model_name='libros',
            name='categoria',
            field=models.ManyToManyField(to='tasks.categoria'),
        ),
    ]
