# Generated by Django 5.2 on 2025-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_categoria_alter_libros_año_remove_libros_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='libros',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libros',
            name='ejemplares_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libros',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='libros',
            name='categoria',
            field=models.CharField(choices=[('romance', 'Romance'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('ciencia', 'Ciencia Ficción'), ('terror', 'Terror'), ('drama', 'Drama'), ('comedia', 'Comedia'), ('fantasia', 'Fantasía')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
