# Generated by Django 5.2 on 2025-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_libros_categoria_alter_libros_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='categoria',
            field=models.CharField(choices=[('romance', 'Romance'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('ciencia', 'Ciencia Ficción'), ('terror', 'Terror'), ('drama', 'Drama'), ('comedia', 'Comedia'), ('fantasia', 'Fantasía'), ('historia', 'Histórica'), ('biografia', 'Biografía'), ('misterio', 'Misterio'), ('poesia', 'Poesía'), ('educativo', 'Educativo'), ('infantil', 'Infantil')], max_length=20),
        ),
    ]
