# Generated by Django 5.2 on 2025-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_libros_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
