# Generated by Django 5.2 on 2025-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_libros_descripcion_libros_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='edicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='formato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='idioma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='num_paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
