# Generated by Django 5.2 on 2025-05-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_libros_edicion_libros_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='fecha_publicacion',
        ),
    ]
