# Generated by Django 5.2 on 2025-05-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_libros_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='edicion',
            field=models.CharField(blank=True, choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera'), ('especial', 'Edición especial'), ('revisada', 'Edición revisada')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='formato',
            field=models.CharField(blank=True, choices=[('tapa_blanda', 'Tapa blanda'), ('tapa_dura', 'Tapa dura'), ('ebook', 'Ebook'), ('audiolibro', 'Audiolibro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='idioma',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués')], max_length=50, null=True),
        ),
    ]
