# Generated by Django 5.2 on 2025-05-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_libros_edicion_alter_libros_formato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='descripcion',
        ),
    ]
