# Generated by Django 5.1.7 on 2025-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_libros_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='categoria',
            field=models.CharField(choices=[('romance', 'Romance'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('ciencia', 'Ciencia Ficción'), ('terror', 'Terror'), ('drama', 'Drama'), ('comedia', 'Comedia'), ('fantasia', 'Fantasía'), ('historia', 'Histórica'), ('biografia', 'Biografía'), ('misterio', 'Misterio'), ('poesia', 'Poesía'), ('educativo', 'Educativo'), ('infantil', 'Infantil'), ('belica', 'Bélica'), ('juvenil', 'Juvenil')], max_length=20),
        ),
    ]
