# Generated by Django 5.1.7 on 2025-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_libros_subcategoria_alter_libros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='categoria',
            field=models.CharField(choices=[('romance', 'Romantica'), ('accion', 'Acción'), ('aventura', 'Aventura'), ('ciencia', 'Ciencia Ficción'), ('terror', 'Terror'), ('drama', 'Drama'), ('comedia', 'Comedia'), ('fantasia', 'Fantasía'), ('historia', 'Histórica'), ('biografia y autobiografia', 'Biografía y Autobiografía'), ('misterio', 'Misterio'), ('poesia', 'Poesía'), ('educativo', 'Educativo'), ('infantil', 'Infantil'), ('belica', 'Bélica'), ('juvenil', 'Juvenil'), ('saga', 'Saga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='libros',
            name='formato',
            field=models.CharField(blank=True, choices=[('tapa_blanda', 'Tapa blanda'), ('tapa_dura', 'Tapa dura'), ('audiolibro', 'Audiolibro')], max_length=100, null=True),
        ),
    ]
